import asyncio
import os
from dotenv import load_dotenv

os.chdir("backend")
load_dotenv('.env')

from app.services.voice import generate_audio_alert

async def test():
    bytes_data = await generate_audio_alert("Evacuate immediately.")
    print(f"Generated bytes length: {len(bytes_data)}")
    if len(bytes_data) > 1000:
        print("SUCCESS")
    else:
        print("FAILED")

if __name__ == "__main__":
    asyncio.run(test())
