import asyncio
import os
import sys

from dotenv import load_dotenv
load_dotenv('.env')

from google import genai
from google.genai import types

async def test():
    api_key = os.environ.get("GEMINI_API_KEY")
    client = genai.Client(api_key=api_key)
    print("Testing generate_audio_alert...")
    
    response = await client.aio.models.generate_content(
        model='gemini-2.0-flash-exp',
        contents="Evacuate immediately.",
        config=types.GenerateContentConfig(
            response_modalities=["AUDIO"],
            speech_config=types.SpeechConfig(
                voice_config=types.VoiceConfig(
                    prebuilt_voice_config=types.PrebuiltVoiceConfig(
                        voice_name="Puck"
                    )
                )
            ),
        ),
    )
    if hasattr(response.candidates[0].content.parts[0], 'inline_data'):
        bytes_data = response.candidates[0].content.parts[0].inline_data.data
        print(f"Generated bytes length: {len(bytes_data)}")
        if len(bytes_data) > 1000:
            print("SUCCESS")
        else:
            print("FAILED")
    else:
        print("FAILED: No inline data.")

if __name__ == "__main__":
    asyncio.run(test())
