name: Build Flutter APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set Up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'
          channel: 'stable'

      - name: Generate Android Workspace
        working-directory: ./frontend-mobile
        run: flutter create --platforms android .

      - name: Configure Android Permissions
        working-directory: ./frontend-mobile
        run: |
          sed -i '/<application/i \    <uses-permission android:name="android.permission.INTERNET" />\n    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />\n    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />' android/app/src/main/AndroidManifest.xml

      - name: Inject Environment Variables
        working-directory: ./frontend-mobile
        run: |
          echo "API_BASE_URL=http://172.16.41.134:8000/api" > .env

      - name: Install Dependencies
        working-directory: ./frontend-mobile
        run: flutter pub get

      - name: Build APK
        working-directory: ./frontend-mobile
        run: flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: frontend-mobile/build/app/outputs/flutter-apk/app-release.apk
